version: '3'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    environment:
      NODE_ENV: production

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://backend:3000 
    container_name: frontend
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
    
networks:
  app-network:
    driver: bridge