# Dockerfile pour le Backend (Node.js)
FROM node:18

# Crée un répertoire de travail
WORKDIR /usr/src/app

# Copie package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie le reste du code de l'application
COPY . .

# Expose le port 3000 (ou autre si configuré différemment dans app.js)
EXPOSE 3000

# Commande pour démarrer le serveur backend
CMD ["node", "app.js"]
